[2021-03-25 14:58:15,259] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: EDGAR-Inference-Pipeline.preprocess 2021-03-25T21:57:57.970562+00:00 [queued]>
[2021-03-25 14:58:15,268] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: EDGAR-Inference-Pipeline.preprocess 2021-03-25T21:57:57.970562+00:00 [queued]>
[2021-03-25 14:58:15,269] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-25 14:58:15,269] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-25 14:58:15,269] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-25 14:58:15,280] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): preprocess> on 2021-03-25T21:57:57.970562+00:00
[2021-03-25 14:58:15,283] {standard_task_runner.py:52} INFO - Started process 5059 to run task
[2021-03-25 14:58:15,292] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'EDGAR-Inference-Pipeline', 'preprocess', '2021-03-25T21:57:57.970562+00:00', '--job-id', '42', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/edgar_inference.py', '--cfg-path', '/var/folders/_j/s8vbc0cs1fvgclq8hnvtq1wm0000gn/T/tmpn4htiu_g', '--error-file', '/var/folders/_j/s8vbc0cs1fvgclq8hnvtq1wm0000gn/T/tmp56jvwh0w']
[2021-03-25 14:58:15,294] {standard_task_runner.py:77} INFO - Job 42: Subtask preprocess
[2021-03-25 14:58:15,338] {logging_mixin.py:104} INFO - Running <TaskInstance: EDGAR-Inference-Pipeline.preprocess 2021-03-25T21:57:57.970562+00:00 [running]> on host prathyushas-mbp.home
[2021-03-25 14:58:15,363] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=EDGAR-Inference-Pipeline
AIRFLOW_CTX_TASK_ID=preprocess
AIRFLOW_CTX_EXECUTION_DATE=2021-03-25T21:57:57.970562+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-25T21:57:57.970562+00:00
[2021-03-25 14:58:15,368] {logging_mixin.py:104} INFO - ['CELTF', 'ACFN', 'KGFHF', 'BLFS', 'IRIX', 'BMMJ', 'GHLD', 'TME']
[2021-03-25 14:58:15,680] {credentials.py:1217} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2021-03-25 14:58:20,290] {python.py:118} INFO - Done. Returned value was: None
[2021-03-25 14:58:20,295] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=EDGAR-Inference-Pipeline, task_id=preprocess, execution_date=20210325T215757, start_date=20210325T215815, end_date=20210325T215820
[2021-03-25 14:58:20,312] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-03-25 14:58:20,323] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2021-03-25 14:58:20,331] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 5059
