[2021-03-17 19:29:24,804] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: taxi.ExampleValidator 2021-03-17T23:28:18.372751+00:00 [queued]>
[2021-03-17 19:29:24,823] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: taxi.ExampleValidator 2021-03-17T23:28:18.372751+00:00 [queued]>
[2021-03-17 19:29:24,823] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-17 19:29:24,823] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-17 19:29:24,823] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-17 19:29:24,838] {taskinstance.py:1063} INFO - Executing <Task(AirflowComponent): ExampleValidator> on 2021-03-17T23:28:18.372751+00:00
[2021-03-17 19:29:24,843] {standard_task_runner.py:52} INFO - Started process 29171 to run task
[2021-03-17 19:29:24,859] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'taxi', 'ExampleValidator', '2021-03-17T23:28:18.372751+00:00', '--job-id', '20', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/taxi_pipeline.py', '--cfg-path', '/var/folders/j6/755w2l7n4x1c9313788klj880000gq/T/tmp2a104t6j', '--error-file', '/var/folders/j6/755w2l7n4x1c9313788klj880000gq/T/tmp2io8xrv9']
[2021-03-17 19:29:24,863] {standard_task_runner.py:77} INFO - Job 20: Subtask ExampleValidator
[2021-03-17 19:29:24,917] {logging_mixin.py:104} INFO - Running <TaskInstance: taxi.ExampleValidator 2021-03-17T23:28:18.372751+00:00 [running]> on host 152.1.168.192.in-addr.arpa
[2021-03-17 19:29:24,966] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=taxi
AIRFLOW_CTX_TASK_ID=ExampleValidator
AIRFLOW_CTX_EXECUTION_DATE=2021-03-17T23:28:18.372751+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-17T23:28:18.372751+00:00
[2021-03-17 19:29:24,974] {base_component_launcher.py:196} INFO - Running driver for ExampleValidator
[2021-03-17 19:29:24,982] {metadata_store.py:93} INFO - MetadataStore with DB connection initialized
[2021-03-17 19:29:25,025] {base_component_launcher.py:212} INFO - Running publisher for ExampleValidator
[2021-03-17 19:29:25,027] {metadata_store.py:93} INFO - MetadataStore with DB connection initialized
[2021-03-17 19:29:25,029] {python.py:118} INFO - Done. Returned value was: None
[2021-03-17 19:29:25,035] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=taxi, task_id=ExampleValidator, execution_date=20210317T232818, start_date=20210317T232924, end_date=20210317T232925
[2021-03-17 19:29:25,053] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-03-17 19:29:25,091] {local_task_job.py:146} INFO - Task exited with return code 0
